apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - configmap.yaml
patches:
  - target:
      group: buildrlabs.io
      version: v1
      kind: MicrosoftSentinelAnalyticRule
      name: example-analytic-rule-1
    path: ../../../microsoft_sentinel/analytic_rules/common_patches/disable_analytic_rule.yaml