apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - configmap.yaml
patches:
  - target:
      group: buildrlabs.io
      version: v1
      kind: MicrosoftSentinelDetectionRule
      name: example-detection-rule-1
    path: ../../../common_patches/disable_detection_rule.yaml