apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: d4c3b2a1-detection-rules
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/tenants/d4c3b2a1/production
  targetNamespace: d4c3b2a1
  prune: true