apiVersion: buildrlabs.io/v1
kind: MicrosoftSentinelDetectionRule
metadata:
  name: example-rule-1
  namespace: a1b2c3d4
spec:
  name: Example 1
  enabled: true
  description: This is the Detection Rule description
  query: >
    Resources
      | where type == 'microsoft.keyvault/vaults'
      | extend publicAccess = properties.publicNetworkAccess
      | where publicAccess == 'Enabled'
      | project name, location, resourceGroup, subscriptionId
  queryFrequency: PT1H
  queryPeriod: P2DT1H30M
  severity: High
  triggerOperator: Equal
  suppressionEnabled: false
  entityMappings:
    - entityType: Host
      fieldMappings:
        - identifier: FullName
          columnName: Computer
  eventGroupingSettings:
    aggregationKind: AlertPerResult
  