apiVersion: buildrlabs.io/v1
kind: MicrosoftSentinelDetectionRule
metadata:
  name: example-detection-rule-3
spec:
  properties:
    displayName: Example Rule 3
    enabled: true
    description: This is a different description
    query: Heartbeat `${example-macro-1}`
    queryFrequency: PT1H
    queryPeriod: P2DT1H30M
    severity: Medium
    suppressionDuration: PT15H
    suppressionEnabled: false
    triggerOperator: Equal
    triggerThreshold: 1
    entityMappings:
      - entityType: Host
        fieldMappings:
          - identifier: FullName
            columnName: Computer
    eventGroupingSettings:
      aggregationKind: AlertPerResult