apiVersion: buildrlabs.io/v1
kind: MicrosoftSentinelDetectionRule
metadata:
  name: example-rule-1
spec:
  name: Example 1
  enabled: true
  description: This is the Detection Rule description
  query: |
    let Threshold = 25;
    let TimeFrame = 1h;
    AzureActivity
    | where OperationNameValue =~ "MICROSOFT.COMPUTE/VIRTUALMACHINES/START/ACTION"
    | where ActivityStatusValue == "Success"
    | extend ResourceName = tostring(parse_json(Properties).resource)
    | summarize Total = dcount(ResourceName), ResourceNames = make_set(ResourceName) by bin(TimeGenerated, TimeFrame), SubscriptionId, ResourceId
    | where Total >= Threshold
  queryFrequency: PT1H
  queryPeriod: P2DT1H30M
  severity: High
  triggerOperator: Equal
  suppressionEnabled: false
  entityMappings:
    - entityType: Host
      fieldMappings:
        - identifier: FullName
          columnName: TimeGenerated
  eventGroupingSettings:
    aggregationKind: AlertPerResult
  