apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microsoftsentineldetectionrules.buildrlabs.io
spec:
  group: buildrlabs.io
  names:
    categories: []
    kind: MicrosoftSentinelDetectionRule
    plural: microsoftsentineldetectionrules
    shortNames:
    - msd
    - msds
    singular: microsoftsentineldetectionrule
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Checks if the Detection Rule is deployed to Microsoft Sentinel
      jsonPath: .status.create_detection_rule.deployed
      name: Status
      type: string
    - description: Checks if the Detection Rule is enabled in Microsoft Sentinel
      jsonPath: .status.create_detection_rule.enabled
      name: Enabled
      type: string
    - description: Additional information about the deployment status
      jsonPath: .status.create_detection_rule.message
      name: Message
      type: string
    - description: The type of Microsoft Sentinel Detection Rule
      jsonPath: .status.create_detection_rule.rule_type
      name: Rule type
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MicrosoftSentinelDetectionRuleSpec via `CustomResource`
        properties:
          spec:
            properties:
              query:
                type: string
              query_prefix:
                nullable: true
                type: string
              query_suffix:
                nullable: true
                type: string
            required:
            - query
            type: object
          status:
            nullable: true
            properties:
              deployed:
                type: string
              enabled:
                type: string
              message:
                type: string
              rule_type:
                type: string
            required:
            - deployed
            - enabled
            - message
            - rule_type
            type: object
        required:
        - spec
        title: MicrosoftSentinelDetectionRule
        type: object
    served: true
    storage: true
    subresources:
      status: {}
