apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microsoftsentinelautomationrules.buildrlabs.io
spec:
  group: buildrlabs.io
  names:
    categories: []
    kind: MicrosoftSentinelAutomationRule
    plural: microsoftsentinelautomationrules
    shortNames:
    - msar
    - msars
    singular: microsoftsentinelautomationrule
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Checks if the Automation Rule is deployed to Microsoft Sentinel
      jsonPath: .status.create_automation_rule.deployed
      name: Status
      type: string
    - description: Checks if the Automation Rule is enabled in Microsoft Sentinel
      jsonPath: .status.create_automation_rule.enabled
      name: Enabled
      type: string
    - description: Additional information about the deployment status
      jsonPath: .status.create_automation_rule.message
      name: Message
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MicrosoftSentinelAutomationRuleSpec via `CustomResource`
        properties:
          spec:
            properties:
              properties:
                properties:
                  actions:
                    items:
                      oneOf:
                      - required:
                        - ModifyPropertiesAction
                      - required:
                        - AddIncidentTagAction
                      - required:
                        - RunPlaybookAction
                      properties:
                        AddIncidentTagAction:
                          properties:
                            actionConfiguration:
                              properties:
                                description:
                                  type: string
                                title:
                                  type: string
                              required:
                              - description
                              - title
                              type: object
                            actionType:
                              enum:
                              - Add Incident Task
                              type: string
                            order:
                              format: int64
                              type: integer
                          required:
                          - actionConfiguration
                          - actionType
                          - order
                          type: object
                        ModifyPropertiesAction:
                          properties:
                            actionConfiguration:
                              properties:
                                classification:
                                  enum:
                                  - BenignPositive
                                  - FalsePositive
                                  - TruePositive
                                  - Undetermined
                                  type: string
                                classificationComment:
                                  type: string
                                classificationReason:
                                  enum:
                                  - InaccurateData
                                  - IncorrectAlertLogic
                                  - SuspiciousActivity
                                  - SuspiciousButExpected
                                  type: string
                                labels:
                                  items:
                                    properties:
                                      labelName:
                                        type: string
                                      labelType:
                                        enum:
                                        - AutoAssigned
                                        - User
                                        type: string
                                    required:
                                    - labelName
                                    - labelType
                                    type: object
                                  type: array
                                owner:
                                  properties:
                                    assignedTo:
                                      type: string
                                    email:
                                      type: string
                                    objectId:
                                      type: string
                                    ownerType:
                                      enum:
                                      - Group
                                      - Unknown
                                      - User
                                      type: string
                                    userPrincipalName:
                                      type: string
                                  required:
                                  - assignedTo
                                  - email
                                  - objectId
                                  - ownerType
                                  - userPrincipalName
                                  type: object
                                severity:
                                  enum:
                                  - High
                                  - Medium
                                  - Low
                                  - Informational
                                  type: string
                                status:
                                  enum:
                                  - Active
                                  - Closed
                                  - New
                                  type: string
                              required:
                              - classification
                              - classificationComment
                              - classificationReason
                              - labels
                              - owner
                              - severity
                              - status
                              type: object
                            actionType:
                              enum:
                              - Modify Properties
                              type: string
                            order:
                              format: int64
                              type: integer
                          required:
                          - actionConfiguration
                          - actionType
                          - order
                          type: object
                        RunPlaybookAction:
                          properties:
                            actionConfiguration:
                              properties:
                                logicAppResourceId:
                                  type: string
                                tenantId:
                                  type: string
                              required:
                              - logicAppResourceId
                              - tenantId
                              type: object
                            actionType:
                              enum:
                              - Run Playbook
                              type: string
                            order:
                              format: int64
                              type: integer
                          required:
                          - actionConfiguration
                          - actionType
                          - order
                          type: object
                      type: object
                    type: array
                  displayName:
                    type: string
                  order:
                    format: int64
                    type: integer
                  triggeringLogic:
                    type: object
                required:
                - actions
                - displayName
                - order
                - triggeringLogic
                type: object
            required:
            - properties
            type: object
          status:
            nullable: true
            properties:
              deployed:
                type: string
              enabled:
                type: string
              message:
                type: string
            required:
            - deployed
            - enabled
            - message
            type: object
        required:
        - spec
        title: MicrosoftSentinelAutomationRule
        type: object
    served: true
    storage: true
    subresources:
      status: {}
