apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microsoftsentinelmacros.buildrlabs.io
spec:
  scope: Namespaced
  group: buildrlabs.io
  names:
    kind: MicrosoftSentinelMacro
    plural: microsoftsentinelmacros
    singular: microsoftsentinelmacro
    shortNames:
      - mscs
      - msc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true