apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microsoftsentineldetectionrules.buildrlabs.io
spec:
  scope: Namespaced
  group: buildrlabs.io
  names:
    kind: MicrosoftSentinelDetectionRule
    plural: microsoftsentineldetectionrules
    singular: microsoftsentineldetectionrule
    shortNames:
      - msds
      - msd
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true